CREATE TABLE Likes (
    IdArticle INT NOT NULL,
    IdUser INT NOT NULL,
    Date DATETIME NOT NULL DEFAULT GETDATE(),
    
    CONSTRAINT PK_Likes PRIMARY KEY (IdArticle, IdUser),
    CONSTRAINT FK_Likes_Article FOREIGN KEY (IdArticle) 
        REFERENCES Articles(IdArticle) ON DELETE CASCADE,
    CONSTRAINT FK_Likes_User FOREIGN KEY (IdUser) 
        REFERENCES Users(IdUser) ON DELETE CASCADE
);
GO