CREATE TABLE Icons (
    IdIcon INT IDENTITY(1,1) NOT NULL,
    Title NVARCHAR(100) NOT NULL,
    Resource NVARCHAR(500) NOT NULL,
    Color NVARCHAR(50) NULL,
    Category NVARCHAR(200) NULL,
    Type NVARCHAR(50) NULL,
    
    CONSTRAINT PK_Icons PRIMARY KEY CLUSTERED (IdIcon),
    CONSTRAINT UX_Icons_Name UNIQUE NONCLUSTERED (Title)
);
GO